### ISSUE TITLE
HSF support

### ISSUE THREAD

**Issue by thorsted** [KBNLresearch/isolyzer#26]
The High Sierra Format was the standard in CD publishing until ISO 9660 became the standard.

Described [here](https://www.os2museum.com/wp/looking-for-high-sierra/)

Sample [here](https://archive.org/details/MS_BOOKSHELF_87)

**Comment by bitsgalore** [comment]
Interesting, I also came across this technical note from Apple which highlights the main differences between High Sierrra and ISO 9660:
<https://www.tech-insider.org/mac/research/acrobat/8808.pdf>

**Comment by bitsgalore** [comment]
Done, <https://github.com/KBNLresearch/isolyzer/releases/tag/1.4.0a2>
