### ISSUE TITLE
Expert Witness Disk Image Format

### ISSUE THREAD

**Issue by thorsted** [KBNLresearch/isolyzer#31]
Wondering if it might be possible to support the EWF format. Mostly the .E01 format, but has a few varieties.

[LOC EWF Family](https://www.loc.gov/preservation/digital/formats/fdd/fdd000406.shtml)

[EWF Tools](https://github.com/libyal/libewf)

**Comment by bitsgalore** [comment]
Not sure about this, at first glace EWF looks like something that's not really within the scope of Isolyzer. Isolyzer was primarily created to analyze file systems that are specific to optical media, whereas EWF is a more generic container format. Likewise, Isolyzer doesn't support (and won't support) file systems like the various FAT variants, NTFS, EXT3, EXT4 and so on, or container formats like ZIP.

**Comment by thorsted** [comment]
Makes sense. Not a huge fan of the format within the Digital Preservation space, but does embed some great descriptive metadata with it. Thanks for looking.
